@host = http://localhost:5032/api

GET {{host}}/todos/910/10?sortby=0


###
GET {{host}}/todos/1

// https://mysite.com/api/v1/todos/1
// https://mysite.com/api/v2/todos/1


###

POST {{host}}/todos
Content-Type: application/json

{
    "title": "MySuperTitle",
    "description": "MySuperDescription",
    "priority": 0
}


###

GET {{host}}/todos/dump