@host = http://26.76.43.135:5032/api

GET {{host}}/todos/910/10?sortby=0

###
GET {{host}}/todos/-999
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWxleCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ik93bmVyIiwiZXhwIjoxNzQwNTA0NjI5LCJpc3MiOiJUb0RvQVBJIiwiYXVkIjoiVVNFUiJ9.rqt9e0bUNV81YOOjqltXhV26OCEkwKVIS-wxF00IAMw

###

GET {{host}}/todos/10/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJMb2dpbiI6ImFsZXgyMjgiLCJleHAiOjE3MzkxMjAwNzMsImlzcyI6IlRvRG9BUEkiLCJhdWQiOiJVU0VSIn0.zMm9jACqbl4Fwcu54augdhVZeWuVMnn-D0W70pcWbnY

###

POST {{host}}/todos
Content-Type: application/json

{
	"title": "MySuperTitle",
	"description": "MySuperDescription",
	"priority": 0
}


###

GET {{host}}/todos/dump

###

POST {{host}}/signup
Content-Type: application/json

{
	"Login": "alex",
	"Password": "alex"
}

###
POST {{host}}/signin
Content-Type: application/json

{
	"Login": "alex",
	"Password": "alex"
}

###

POST {{host}}/refresh
Content-Type: application/json

"c8756b4b0180fa8f5a3b0ec882fd3e7a87d5da3ed7eec06902219b53ee71dacc"

###

GET http://localhost:5032/ooo



###

GET {{host}}/claims
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWxleCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ik93bmVyIiwiZXhwIjoxNzQwNTAzNDcyLCJpc3MiOiJUb0RvQVBJIiwiYXVkIjoiVVNFUiJ9._F-s4CDQiQbSLifFBcE_EnqDFProrukfs9ABzDvSQGQ


###

GET {{host}}/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWxleCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkJhbm5lZCIsImV4cCI6MTc0MDUwMzU2NiwiaXNzIjoiVG9Eb0FQSSIsImF1ZCI6IlVTRVIifQ.-Ovg8JEFv_CiCXr2tvcNLVnoJjm6BIGHZxu1qbuV1MQ