@host = http://localhost:5032/api

GET {{host}}/todos/910/10?sortby=0


###
GET {{host}}/todos/-1

// https://mysite.com/api/v1/todos/1
// https://mysite.com/api/v2/todos/1

###

GET {{host}}/todos/10/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJMb2dpbiI6ImFsZXgyMjgiLCJleHAiOjE3MzkxMjAwNzMsImlzcyI6IlRvRG9BUEkiLCJhdWQiOiJVU0VSIn0.zMm9jACqbl4Fwcu54augdhVZeWuVMnn-D0W70pcWbnY

###

POST {{host}}/todos
Content-Type: application/json

{
    "title": "MySuperTitle",
    "description": "MySuperDescription",
    "priority": 0
}


###

GET {{host}}/todos/dump

###

POST {{host}}/signup
Content-Type: application/json

{
    "Login": "alex228",
    "Password": "3.14Door_A2S"
}

###
POST {{host}}/login
Content-Type: application/json

{
	"Login": "alex",
	"Password": "alex"
}


###

GET {{host}}/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJMb2dpbiI6ImFsZXgyMjgiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTczOTI4NzkyOCwiaXNzIjoiVG9Eb0FQSSIsImF1ZCI6IlVTRVIifQ.W082NTaETew8DpHNmiTNfw9hha0Ya3YqWsFAmP4Vg2U