@host = http://localhost:5032/api

GET {{host}}/todos/910/10?sortby=0

###
GET {{host}}/todos/1

// https://mysite.com/api/v1/todos/1
// https://mysite.com/api/v2/todos/1

###

GET {{host}}/todos/10/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJMb2dpbiI6ImFsZXgyMjgiLCJleHAiOjE3MzkxMjAwNzMsImlzcyI6IlRvRG9BUEkiLCJhdWQiOiJVU0VSIn0.zMm9jACqbl4Fwcu54augdhVZeWuVMnn-D0W70pcWbnY

###

POST {{host}}/todos
Content-Type: application/json

{
	"title": "MySuperTitle",
	"description": "MySuperDescription",
	"priority": 0
}


###

GET {{host}}/todos/dump

###

POST {{host}}/signup
Content-Type: application/json

{
	"Login": "alex",
	"Password": "alex"
}

###
POST {{host}}/login HTTP/2
Content-Type: application/json

{
	"Login": "alex",
	"Password": "aleh"
}




###
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWxleCIsImV4cCI6MTczOTQ2NTUzNywiaXNzIjoiVG9Eb0FQSSIsImF1ZCI6IlVTRVIifQ.5lE9NpkcbvUHTCDvOS93WuGdjimP_lyYD6RrRmeW_6o
### c987cf8ffac0ca073fcc4ad66b67d87184a6d1d5ec65735f26dead0c602c8c06

GET {{host}}/login_info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWxleCIsImV4cCI6MTczOTQ2NTUzNywiaXNzIjoiVG9Eb0FQSSIsImF1ZCI6IlVTRVIifQ.5lE9NpkcbvUHTCDvOS93WuGdjimP_lyYD6RrRmeW_6o

###

POST {{host}}/refresh
Content-Type: application/json

"c987cf8ffac0ca073fcc4ad66b67d87184a6d1d5ec65735f26dead0c602c8c06"

###

GET {{host}}/v1/my_todos?offset=-6&count=-10

###

GET http://localhost:5032/ooo




